In [2]:
#
# Created by Homayoun Heidarzadeh
#
from base.impovedwdknn import ImprovedWDKNN
from data import data
import numpy as np
from glob import glob

if __name__ == '__main__':
    # prepare data
    # generate predictions
    results = []
    for name in glob("data/wdknn/*.txt"):
        print "For", name
        X = data.load_data(name, delm=',')[:, :-1]
        label = data.load_data(name, delm=',', dtype=int)[:, -1]
        np.random.seed(0)
        permutaion = np.random.permutation(X.shape[0])
        X = X[permutaion]
        label = label[permutaion]
        X = (X - X.mean(axis=0)) / X.std(axis=0)
        result = ImprovedWDKNN.cross_validation_for_k([1, 2, 3, 4, 5], X, label)
        print result
        results.append(result)
    print "Overall Avgs -->"
    print np.mean(results, axis=0)

For data/wdknn/ecoli0267vs35.txt
[ 0.878       0.67        0.72498413  0.7981435 ]
For data/wdknn/ecoli3.txt
[ 0.63280952  0.57142857  0.5639019   0.72685806]
For data/wdknn/yeast0256vs3789.txt
[ 0.63507433  0.54526316  0.57901207  0.72219889]
For data/wdknn/yeast02579vs368.txt
[ 0.80033339  0.80210526  0.79793325  0.88495269]
For data/wdknn/yeast0359vs78.txt
[ 0.51968254  0.384       0.42878342  0.59984799]
For data/wdknn/yeast2vs4.txt
[ 0.85172294  0.712       0.76162378  0.83296637]
For data/wdknn/yeast3.txt
[ 0.75232686  0.7175      0.73064641  0.83229176]
Overall Avgs -->
[ 0.72427851  0.62889957  0.65526928  0.77103704]
