In [2]:
#
# Created by Homayoun Heidarzadeh
#
from base.wdknn import WDKNN
from data import data
import numpy as np
from glob import glob

if __name__ == '__main__':
    # prepare data
    # generate predictions
    results = []
    for name in glob("data/wdknn/*.txt"):
        print "For", name.split("/")[-1]
        X = data.load_data(name, delm=',')[:, :-1]
        label = data.load_data(name, delm=',', dtype=int)[:, -1]
        np.random.seed(0)
        permutaion = np.random.permutation(X.shape[0])
        X = X[permutaion]
        label = label[permutaion]
        X = (X - X.mean(axis=0)) / X.std(axis=0)
        result = WDKNN.cross_validation_for_k([1, 2, 3, 4, 5], X, label)
        print result
        results.append(result)
    print "Overall Avgs -->"
    print np.mean(results, axis=0)

For ecoli0267vs35.txt
[ 0.904       0.63        0.69815873  0.75958558]
For ecoli3.txt
[ 0.66568254  0.55428571  0.57289909  0.719467  ]
For yeast0256vs3789.txt
[ 0.65661892  0.53052632  0.57678239  0.71250025]
For yeast02579vs368.txt
[ 0.80701996  0.78736842  0.79326046  0.87725984]
For yeast0359vs78.txt
[ 0.55655556  0.36        0.42224178  0.58190214]
For yeast2vs4.txt
[ 0.87031313  0.692       0.75373367  0.82123751]
For yeast3.txt
[ 0.76308734  0.7075      0.73030912  0.8274564 ]
Overall Avgs -->
[ 0.74618249  0.60881149  0.64962646  0.75705839]
